services:
  pipeline:
    build: ./src/prepare
    volumes:
      - ./data:/app/data
      - ./model:/app/model
      - ./src:/app/src
    command: >
      sh -c "
        echo '===> Running data stage (raw)...' &&
        python src/prepare/dataset/data_processing.py --raw &&
        echo '===> Running data stage (process)...' &&
        python src/prepare/dataset/data_processing.py --process &&
        echo '===> Running model training...' &&
        python src/prepare/model/train_mlflow.py &&
        echo '===> Pipeline finished.'
      "
    ports:
      - "5000:5000"  # для MLflow UI
    environment:
      - PYTHONPATH=/app
    
  api:
    build: ./src/api
    depends_on:
      - pipeline
    volumes:
      - ./model:/app/model
      - ./src/api:/app/src/api
      - ./src/prepare:/app/src/prepare
    command: >
      uvicorn src.api.api:app --host 0.0.0.0 --port 8085
    ports:
      - "8085:8085"

  app:
    build: ./src/app
    depends_on:
      - api
    volumes:
      - ./src/app:/app/src/app
    command: >
      streamlit run src/app/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
