# 1. call data processing functions
# 2. build and train model
# 3. save model
# 4. Connect model to api
FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

